# Generated by Django 4.0.4 on 2022-07-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.FloatField(blank=True, default=0, help_text='use . not ,', null=True)),
            ],
        ),
    ]
