# Generated by Django 4.0.4 on 2022-07-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nft_12_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nft_13_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='nft_14_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nft_19_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='nft_19_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nft_19_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nft_20_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='nft_20_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nft_20_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_1_image',
            field=models.ImageField(help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_1_price',
            field=models.FloatField(help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_1_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
