# Generated by Django 4.0.4 on 2022-07-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_case_delete_coinbaseorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='domain_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='template_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_img',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
