# Generated by Django 4.0.4 on 2022-07-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_domain_name_profile_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('basic', 'basic'), ('pro', 'pro'), ('business', 'business')], max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
